---
- name: Update packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes
    force_apt_get: yes
    autoremove: yes
    autoclean: yes
  become: yes

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  tags:
    - hostname

- name: Set timezone
  ansible.builtin.timezone:
    name: "{{ timezone }}"
  tags:
    - timezone
