---
# tasks file for host_config
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  tags:
    - hostname

- name: Set timezone
  timezone:
    name: "{{ timezone }}"
  tags:
    - timezone

- name: Set MOTD
  template:
    src: motd.j2
    dest: /etc/motd
  tags:
    - motd