---
- name: Restart Odoo
  ansible.builtin.systemd:
    name: odoo
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: yes

- name: Stop Odoo
  ansible.builtin.systemd:
    name: odoo
    state: stopped
    daemon_reload: yes
  become: yes

- name: Reload UFW
  community.general.ufw:
    state: reloaded
  become: yes