---
# tasks file for webserver
- name: Create directory for python webserver
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    mode: 0755

- name: Copy index.j2 to webserver directory
  ansible.builtin.copy:
    src: files/index.j2
    dest: /var/www/html/index.html
    mode: 0644

- name: Install python3
  ansible.builtin.package:
    name: python3
    state: present

- name: Copy python-webserver.service to systemd
  ansible.builtin.copy:
    src: files/python-webserver.service
    dest: /etc/systemd/system/python-webserver.service
    mode: 0644

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Test python-webserver service
  ansible.builtin.systemd:
    name: python-webserver
    state: started
    enabled: yes

- name: Enable python-webserver service
  ansible.builtin.systemd:
    name: python-webserver
    enabled: yes

- name: Curl index page
  ansible.builtin.shell: curl http://localhost:8080
  register: curl_output

- name: Debug output
  ansible.builtin.debug:
      var: curl_output.stdout_lines
